default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  pool: <%= ENV.fetch("DB_POOL", 5) %>
  reaping_frequency: <%= ENV.fetch("DB_REAPING_FREQUENCY", 10) %>
  username: postgres

development:
  <<: *default
  database: hound_development

test:
  <<: *default
  database: hound_test

production:
  pool: <%= [ENV.fetch("MAX_THREADS", 5), ENV.fetch("DB_POOL", 5)].max %>
  url:  <%= ENV.fetch("DATABASE_URL") if Rails.env.production? %>
